FROM node:22-alpine AS builder
WORKDIR /build

ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

COPY package*.json ./
COPY . .
RUN rm -rf node_modules && npm install --frozen-lockfile
RUN npm run build

FROM nginx:stable-alpine AS prod
COPY --from=builder /build/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
