services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:4000
    ports:
      - 80:80

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "4000:3000"
    environment:
      - FRONTEND_URL=http://localhost
      - MONGODB_USER=root
      - MONGODB_PWD=root
      - MONGODB_URI=mongodb://db:27017/techtest-db
    networks:
      - backend_network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=techtest-db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  db_data:
