services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
