FROM node:22-alpine AS builder
WORKDIR /build
COPY package*.json ./
COPY tsconfig*.json ./
COPY ./src ./src
RUN rm -rf node_modules && npm install --frozen-lockfile
RUN npm run build

FROM node:22-alpine AS prod
WORKDIR /app

COPY --from=builder /build/node_modules ./node_modules
COPY --from=builder /build/dist ./dist
COPY --from=builder /build/package*.json ./

EXPOSE 3000
CMD ["npm", "run", "start:prod"]
